language: node_js
node_js:
    - 12
dist: trusty # OS
services:
    - mongodb
    - redis
env:
    - NODE_ENV=ci PORT=3000
cache: # cache installs
    directories:
        - node_modules
        - client/node_modules
install: # project setup
    - npm install
    - npm run build
script:
    - nohup npm run start &
    - sleep 5
    - npm run test
